### ISSUE TITLE
\n within fields

### ISSUE THREAD

**Issue by mdlincoln** [cmoa/collection#1]
It's probably worth warning the user that they will find `\n` interspersed in the provenance fields, as this can (annoyingly) choke some CSV parsers. Do line breaks occur in any other fields?

**Comment by workergnome** [comment]
A quick scan says that  `provenance_text``, ``medium``, and  ``credit_line`` currently all have newlines in their text.  Will add a note about that into the Readme.

**Comment by workergnome** [comment]
Thanks!
