### ISSUE TITLE
Export arrays not as pipe-delimited fields, but rather JSON arrays

### ISSUE THREAD

**Issue by danfowler** [cmoa/collection#17]
Lists of items in a field can be expressed as a JSON array instead:

http://specs.frictionlessdata.io/table-schema/#properties

**Comment by workergnome** [comment]
Except then anyone interpreting the file as CSV would also have to understand how to read and understand JSON, at which point why wouldn't they simply use the JSON dump?  Pipe (or semicolon) delimited fields in CSV are very common and understood by our users.

**Comment by danfowler** [comment]
Yup!  I was half intending to say... "or not!" given how common a use case that is.  In that case, should we add an issue for the specs: https://github.com/frictionlessdata/specs/issues

**Comment by workergnome** [comment]
Thanks for the suggestion, but I don't think we'll implement this at this time.
