### ISSUE TITLE
Specify total number of objects

### ISSUE THREAD

**Issue by mdlincoln** [cmoa/collection#2]
I'd add the expected number of objects to the README (27371 by my count), since #1 means someone might naively run `wc -l cmoa.csv` and get `30128` and get confused.

**Comment by workergnome** [comment]
Let me keep thinking about that—I agree it's a good idea, but the number of objects that we have is dynamic, and I should figure out if there's a robust way to keep that number updated as that data changes.

**Comment by workergnome** [comment]
I have a solution that works for now—it might have to change in the future, but for today I'll accept it.  Thanks!
